### ISSUE TITLE
Deployment issues with Azure Gov

### ISSUE THREAD

**Issue by ms-mikerice** [microsoft/fhir-loader#15]
There are inherent differences between Azure Commercial and Government. Logging this as acknowledgment that I'm working with PG.

**Comment by nkidambi** [comment]
To make this work in Azure Gov, I copied the code, refactored it (not necessary) and made the following changes - 

- Updated the NuGet packages
- Added a new parameter for AAD Login URL instead of hardcoding it (ADUtils.cs).  The urls are document [here](https://learn.microsoft.com/en-us/azure/azure-government/documentation-government-plan-identity).

*Note*: The Authn path works with both oauth2/token and oauth2/v2.0/token. I used the latter. There are changes though. If  oauth2/token is used, we need to pass "resource" in the header ( as it is in the code now). If oauth2/v2.0/token is used, we need to pass "scope" in the header instead of "resource".  Or, you can use DefaultCredentials too.

**Comment by ms-mikerice** [comment]
Here's a fork that works in MAG.
https://github.com/ms-mikerice/fhir-loader/

**Comment by evachen96** [comment]
WebClient has been eliminated; we use the latest Azure Identity Libraries and httpclient which should work with Azure Gov!
